language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wendyi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wendyi/react-test npm test

after_success:
  - docker build -t wendyi/fib-client ./client
  - docker build -t wendyi/fib-nginx ./nginx
  - docker build -t wendyi/fib-server ./server
  - docker build -t wendyi/fib-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push wendyi/fib-client
  - docker push wendyi/fib-nginx
  - docker push wendyi/fib-server
  - docker push wendyi/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fib-react
  env: Fibreact-env
  bucket_name: elasticbeanstalk-us-east-2-844860899486
  bucket_path: fib-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY